#!/bin/bash
# Copyright (C) 2016 Martin Koerner <info@mkoerner.de>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

temp="$(sensors coretemp-isa-0000 | awk '/Package id 0/ { print $4 }' | sed 's/.//' | sed 's/.\{4\}$//')"

echo "$temp°C"
echo "$temp°C"

if [ "$temp" -gt "90" ]
then
  exit 33
else
  if [ "$temp" -gt "80" ]
  then
	  echo "#FF0000"
  else
    if [ "$temp" -gt "70" ]
    then
  	  echo "#FFAE00"
    fi
  fi
fi

exit 0
